### ISSUE TITLE
Please document routes.js

### ISSUE THREAD

**Issue by rosenfeld** [leeluolee/puer#16]
The README mention it follows express.js routes.js specification but it seems the given examples in the README are different from the examples in the documentation:

http://expressjs.com/starter/basic-routing.html

Could you please point to the specific documentation you were referring to or at least change the examples in the README to be like the ones in the Express.js documentation site?

**Comment by leeluolee** [comment]
I add some example about routing with express.Router in puer .

**Comment by rosenfeld** [comment]
Excelent, thanks! :)
