### ISSUE TITLE
windows下无法安装

### ISSUE THREAD

**Issue by bangbang93** [leeluolee/puer#19]
cnpm install -g puer
\
> chokidar@0.8.1 postinstall D:\Program Files\nodejs\node_modules\puer\node_modules\chokidar
> node setup-deps.js

|
> ws@0.4.32 install D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws {git}
{lamb} node "C:\Users\bangbang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws \node_modules\nan\nan.h(1103): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [D:\Program Files\n
odejs\node_mo
dules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws \node_modules\nan\nan.h(1117): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [D:\Program Files\n
odejs\node_mo
dules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\Users\bangbang\.node-gyp\0.10.22\deps\v8\include\v8.h(179): warning C4506: 内联函数“v8::Persistent<T> v8::Pe
rsi
stent<T>::New(v8::Handle<T>)”没有定义 [D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_mo
dul
es\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ]
     正在创建库 D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\
node
  _modules\ws\build\Release\bufferutil.lib 和对象 D:\Program Files\nodejs\node_modules\puer\node_modules\socket
.i
  o\node_modules\socket.io-client\node_modules\ws\build\Release\bufferutil.exp
  正在生成代码
  已完成代码的生成
  bufferutil.vcxproj -> D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.i
  o-client\node_modules\ws\build\Release\\bufferutil.node
  validation.cc
D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws \node_modules\nan\nan.h(1103): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [D:\Program Files\n
odejs\node_mo
dules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws \node_modules\nan\nan.h(1117): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [D:\Program Files\n
odejs\node_mo
dules\puer\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
C:\Users\bangbang\.node-gyp\0.10.22\deps\v8\include\v8.h(179): warning C4506: 内联函数“v8::Persistent<T> v8::Pe
rsi
stent<T>::New(v8::Handle<T>)”没有定义 [D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_mo
dul
es\socket.io-client\node_modules\ws\build\validation.vcxproj]
          with
          [
              T=v8::Object
          ]
     正在创建库 D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.io-client\
node
  _modules\ws\build\Release\validation.lib 和对象 D:\Program Files\nodejs\node_modules\puer\node_modules\socket
.i
  o\node_modules\socket.io-client\node_modules\ws\build\Release\validation.exp
  正在生成代码
  已完成代码的生成
  validation.vcxproj -> D:\Program Files\nodejs\node_modules\puer\node_modules\socket.io\node_modules\socket.i
  o-client\node_modules\ws\build\Release\\validation.node
D:\Program Files\nodejs\puer -> D:\Program Files\nodejs\node_modules\puer\bin\puer

> puer@1.0.9 postinstall D:\Program Files\nodejs\node_modules\puer
> node setup.js

D:\Program Files\nodejs\node_modules\puer\setup.js:31
    if(err) throw err;
                  ^
Error: Command failed:
module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\bangbang\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\bangbang\\.cnpmrc" "--disturl=https://npm.taobao.org/dist" "--cache=C:\\Users\\bangbang\\.npm\\.cache_cnpm" "--registry=https://registry.npm.taobao.org" "install" "-g" "puer"
npm ERR! node v0.10.22
npm ERR! npm  v2.1.4
npm ERR! code ELIFECYCLE

npm ERR! puer@1.0.9 postinstall: `node setup.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the puer@1.0.9 postinstall script.
npm ERR! This is most likely a problem with the puer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node setup.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls puer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Code\kuaiwa-android\www\npm-debug.log

npm路径中有个空格……应该是哪里漏了个引号

**Comment by leeluolee** [comment]
fix in  v1.1.0
