### ISSUE TITLE
setup can't handle spaces in folder structure

### ISSUE THREAD

**Issue by hardythedrummer** [leeluolee/puer#20]
While attempting to install Puer on a windows machine, I ran into an issue where, for some reason, it's trying to grab a module somewhere in the users folder. In my case, that looks something like 'C:\Users\FirstName LastName\' with a space in between names. When I run `npm install -g puer` it comes up with this error message:

> \>node setup.js
> C:\Users\Joey Hardy\AppData\Roaming\npm\node_modules\puer\setup.js:31
>    if(err) throw err;
>                  ^
> Error: Command failed:
> module.js:340
>    throw err;
>          ^
> Error: Cannot find module 'C:\Users\FirstName'

**Comment by hardythedrummer** [comment]
Did eventually find a workaround by changing the "prefix" value in npm config to a folder that doesn't have spaces - probably still worth fixing though :)

**Comment by leeluolee** [comment]
Error may occurs when puer attempt to find the local `coffee` command.

**Comment by leeluolee** [comment]
#19
