### ISSUE TITLE
无法实现实时刷新

### ISSUE THREAD

**Issue by myl0204** [leeluolee/puer#44]
本地服务能起来，但是页面无法实时刷新，控制台报错：Failed to load resource: the server responded with a status of 400 (Bad Request)。
socket.io/1/?t=1495724661270显示{"code":0,"message":"Transport unknown"}
系统是Ubuntu16，之前Windows下用一直没问题的。
跪求海波老师解答

**Comment by KimThomas** [comment]
可以使用1.1.0的版本安装下，我之前也是遇到同样的问题，等作者再提交代码解决BUG之后再下载最新版本。

**Comment by myl0204** [comment]
@KimThomas  试了安装1.1.0版本 还是不行 直接在bash中报错了 浏览器都没起来～ 还是等新版本吧

**Comment by luyis** [comment]
@myl0204 我在Mac下也遇到一样的问题。你现在解决了吗？

**Comment by mejustme** [comment]
+1

**Comment by cpnewobject** [comment]
+1

**Comment by jxycbjhc** [comment]
+1

**Comment by Yibay** [comment]
+1

**Comment by leeluolee** [comment]
已经发布 1.1.3版， 更新了chokidar 的版本，  很感谢这个小东西 还有人在使用  会尽快发布2.0版，  目前的next分支

**Comment by ufologist** [comment]
由于 @leeluolee 在 https://github.com/leeluolee/puer/commit/11cb53057728bfe744e342f90c51ef6699c7a8e0 `1.1.2` 版本后, 将 `socket.io` 升级到了 "~1.7.4"

```
- "socket.io": "0.9.16",
+ "socket.io": "~1.7.4",
```

**但是只是升级了 [Server 端](https://github.com/socketio/socket.io), 没有升级 [Client 端](https://github.com/socketio/socket.io-client)**, 即没有更新 [reload.js](https://github.com/leeluolee/puer/blob/master/vendor/js/reload.js)

在里面用的还是 `Socket.IO.js build:0.9.10`, 版本不兼容, 造成 socket 连接不上, 因此就没有实时刷新了

**Comment by leeluolee** [comment]
@ufologist  PR 已经 publish了  1.1.4

**Comment by Suzichen** [comment]
node v8.9.3
puer v2.0.0
浏览器无法自动刷新，控制台不报错，求解决方案。重装了之前版本的puer也不行...

**Comment by jxycbjhc** [comment]
我刚在mac上面试了一下,版本和你一样，没有任何问题，如果使用nvm版本控制器管理node版本的话，需要在对应的node版本下面全局安装puer。现在好像比之前加了一个检测8000端口是否被占用，递归调用端口加1，直到找到可用端口

在 2018-03-06 10:14:22，"Suzichen" <notifications@github.com> 写道：


node v8.9.3
puer v2.0.0
浏览器无法自动刷新，控制台不报错，求解决方案。重装了之前版本的puer也不行...
